---
services:
  flask:
    image: jerryrondon/flaskapp:0.1.1
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - 7070:8080
    environment:
      - APP_VERSION
      - DB_PASSWORD=${DB_PASSWORD}
