---
services:
  flask:
    image: jerryrondon/flaskapp:0.1.1
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - 7070:8080
    env_file:
      - path: ./flask/dev.env
        required: true
    environment:
      - APP_VERSION
